site_name: Legendary-winner
docs_dir: docs/
repo_name: legendary-winner
repo_url: https://github.com/vkliushta/legendary-winner

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.annotate
