name: Test

on:
  push:
    branches:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test requirements
        run:
          pip install -r reqs/test-requirements.txt

      - name: Run tests
        run:
          python -m pytest tests/ --color=yes
